kind: ReplicationController
apiVersion: v1
metadata:
  name: test-tensorflow-worker
  namespace: test
spec:
  replicas: 2
  selector:
    component: test-tensorflow-worker
  template:
    metadata:
      labels:
        component: test-tensorflow-worker
    spec:
      securityContext:
        runAsUser: 1003
      containers:
        - name: test-tensorflow-worker
          image: nscc/tensorflow:1.3.0-cpu-cluster
          command: ["/tensorflow-worker.sh", "10.103.126.35"]
          ports:
            - containerPort: 2222
            - containerPort: 3333
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /tensorflow
              name: test-tersorflow
      volumes:
      - name: test-tersorflow
        hostPath:
          path: /root/tensorflow
