kind: ReplicationController
apiVersion: v1
metadata:
  name: hadoop-worker
  namespace: zhang
spec:
  replicas: 1
  selector:
    component: hadoop-worker
  template:
    metadata:
      labels:
        component: hadoop-worker
    spec:
      containers:
        - name: hadoop-worker
          image: 192.168.31.85:5523/hadoop:2.7.2
          command: ["/tmp/start-worker-hadoop.sh", "zzymaster"]
          resources:
            requests:
              cpu: 100m
              memory: 2000Mi
