kind: Service
apiVersion: v1
metadata:
  name: test-spark-master
  namespace: test
spec:
  ports:
    - name: terminal
      port: 8000
      targetPort: 8000
    - name: web
      port: 8080
      targetPort: 8080
    - name: master
      port: 7077
      targetPort: 7077
  selector:
    component: test-spark-master
